const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const rows=[['1238','早读 磨耳朵 学英语','奶牛和牛奶','早读课','4-6岁','level 1','是','登录后可看','28(s)','已发布','20000','jiangshuang1','2024-03-28 18:53:28'],['1003','唱儿歌','巴士上的车轮','随身听','0-3岁','level 1','是','所有人可看','81(s)','已发布','19999','zhumin','2019-08-14 17:40:57'],['1005','唱儿歌 早读','ABC','随身听','0-3岁','level 1','是','所有人可看','61(s)','已发布','19999','zhumin','2019-08-14 16:35:17'],['1063','学英语','太空探索','哄睡电台','9岁以上','level 7','否','登录后可看','556(s)','已发布','19990','zhumin','2019-08-14 15:30:39'],['181','唱儿歌','Yally Bally','随身听','7-9岁','level 2','否','所有人可看','55(s)','已发布','19411','sunwanxin_mgt','2019-09-03 22:20:04'],['177','唱儿歌','贝壳','随身听','7-9岁','level 2','否','所有人可看','43(s)','已发布','19011','sunwanxin_mgt','2019-09-03 22:20:27'],['1108','早读 磨耳朵 学英语','摸摸我的鼻子','早读课','4-6岁','level 1','是','所有人可看','31(s)','已发布','18000','zhumin','2019-09-06 16:34:05'],['1109','学英语 磨耳朵 早读','你怎么去学校呢？','早读课','7-9岁','level 2','是','所有人可看','38(s)','已发布','18000','sunwanxin_mgt','2020-03-11 19:04:40'],['1110','早读 磨耳朵 学英语','罗伊的一天（2）','早读课','7-9岁','level 3','是','所有人可看','47(s)','已发布','18000','sunwanxin_mgt','2020-10-23 11:48:44'],['1112','早读 磨耳朵 学英语','名人名言—西奥多·罗斯福系列二','早读课','9岁以上','level 6','是','所有人可看','39(s)','已发布','18000','zhumin','2019-09-16 18:22:03']];
let activeModule='inside';
function render(data){$('#resourceRows').innerHTML=data.map(r=>`<tr>${r.map((v,i)=>`<td>${i===10?`${v} <a class="weight-edit">编辑</a>`:v}</td>`).join('')}<td><button class="row-edit">编辑</button></td></tr>`).join('');$('#emptyState').hidden=!!data.length;$$('.row-edit').forEach(b=>b.onclick=()=>location.href=`index.html?type=${activeModule}`)};render(rows);
$('#collapse').onclick=()=>{$('#sidebar').classList.toggle('collapsed');document.querySelector('.page').classList.toggle('expanded')};$('#addBtn').onclick=()=>location.href=`index.html?type=${activeModule}`;
const resetFilterOutside=()=>{$$('#filterOutsideOptions input').forEach(x=>x.checked=false);$('#filterOutsideText').textContent='请选择课外类型';$('#filterOutsideOptions').hidden=true};
function switchModule(module){activeModule=module;$$('.module-tab').forEach(x=>x.classList.toggle('active',x.dataset.module===module));const outside=module==='outside';$$('.outside-only').forEach(x=>x.hidden=!outside);$('#filterOutsideLevelSimple').hidden=!outside;$('#filterInsideLevelCascade').hidden=outside;if(!outside)resetFilterOutside();$('#filterForm').reset();render(rows);$('#totalText').textContent=outside?'共 559 条':'共 326 条'}
$$('.module-tab').forEach(tab=>tab.onclick=()=>switchModule(tab.dataset.module));
$('#filterOutsideTrigger').onclick=()=>{$('#filterOutsideOptions').hidden=!$('#filterOutsideOptions').hidden};
$$('#filterOutsideOptions input').forEach(x=>x.onchange=()=>{const values=$$('#filterOutsideOptions input:checked').map(i=>i.value);$('#filterOutsideText').textContent=values.length?values.join('、'):'请选择课外类型'});
const fillFilter=(el,count,prefix)=>{el.innerHTML=`<option value="">请选择${prefix}</option>`;for(let i=1;i<=count;i++)el.add(new Option(`${prefix}${i}`,`${prefix}${i}`))};
$('#filterLevelPrimary').onchange=e=>{fillFilter($('#filterUnit'),e.target.value==='L1'?18:15,'Unit');$('#filterUnit').hidden=false;$('#filterLesson').hidden=true};
$('#filterUnit').onchange=()=>{fillFilter($('#filterLesson'),$('#filterLevelPrimary').value==='L1'?8:10,'Lesson');$('#filterLesson').hidden=false};
document.addEventListener('click',e=>{if(!$('#filterOutsideType').contains(e.target))$('#filterOutsideOptions').hidden=true});
$('#filterForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),subtypes=activeModule==='outside'?$$('#filterOutsideOptions input:checked').map(x=>x.value):[];const keys=['age','level','status','hot','radio','power','editor','name'],cols=[4,5,9,6,3,7,11,2];const data=rows.filter(r=>(!subtypes.length||subtypes.some(x=>r[1].includes(x)))&&keys.every((k,i)=>!f.get(k)||String(r[cols[i]]).toLowerCase().includes(String(f.get(k)).toLowerCase())));render(data);$('#totalText').textContent=`共 ${data.length} 条`;show(`查询完成，共 ${data.length} 条`)};$('#filterForm').onreset=()=>setTimeout(()=>{render(rows);$('#totalText').textContent=activeModule==='outside'?'共 559 条':'共 326 条';resetFilterOutside();$('#filterLevelPrimary').value='';$('#filterUnit').hidden=true;$('#filterLesson').hidden=true},0);
$$('.pagination button').forEach(b=>b.onclick=()=>{if(!/^\d+$/.test(b.textContent))return;$$('.pagination button').forEach(x=>x.classList.remove('page-current'));b.classList.add('page-current');show(`已切换至第 ${b.textContent} 页`)});switchModule('inside');function show(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
