const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const form=$('#fmForm'), initial=new FormData(form);
$('#collapse').addEventListener('click',()=>{$('#sidebar').classList.toggle('collapsed');document.querySelector('.page').classList.toggle('expanded')});
$$('input[name="album"]').forEach(r=>r.addEventListener('change',()=>{$('#albumName').disabled=r.value==='default'}));
$$('input[name="publish"]').forEach(r=>r.addEventListener('change',()=>{$('#dateRow').style.display=r.value==='now'?'none':'grid'}));
$$('[data-step]').forEach(btn=>btn.addEventListener('click',()=>{const input=btn.parentElement.querySelector('input');const next=Number(input.value||0)+Number(btn.dataset.step);input.value=Math.max(Number(input.min||0),Math.min(Number(input.max||Infinity),next))}));
$('#cover').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const url=URL.createObjectURL(file);$('#coverPreview').src=url;$('#coverPreview').hidden=false;$('#coverText').hidden=true;$('#largePreview').textContent='';$('#largePreview').style.backgroundImage=`url(${url})`});
$('#audioFile').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const player=$('#audioPreview');player.src=URL.createObjectURL(file);player.hidden=false;$('#audioText').hidden=true;player.onloadedmetadata=()=>{$('#duration').value=Math.round(player.duration||0)}});
form.addEventListener('submit',e=>{e.preventDefault();$$('.error').forEach(x=>x.classList.remove('error'));const missing=['cname','ename'].filter(id=>!$('#'+id).value.trim());if(missing.length){missing.forEach(id=>$('#'+id).classList.add('error'));show('请填写必填项',false);return}show('保存成功（原型演示）',true)});
form.addEventListener('reset',()=>setTimeout(()=>{$('#coverPreview').hidden=true;$('#coverText').hidden=false;$('#largePreview').style.backgroundImage='';$('#largePreview').textContent='353 × 353';$('#audioPreview').hidden=true;$('#audioText').hidden=false;$('#albumName').disabled=true;$('#dateRow').style.display='grid';show('表单已重置',true)},0));
function show(text,ok){const t=$('#toast');t.textContent=text;t.style.color=ok?'#67c23a':'#f56c6c';t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
