const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const form=$('#fmForm'), initial=new FormData(form);
$('#collapse').addEventListener('click',()=>{$('#sidebar').classList.toggle('collapsed');document.querySelector('.page').classList.toggle('expanded')});
$$('input[name="album"]').forEach(r=>r.addEventListener('change',()=>{$('#albumName').disabled=r.value==='default'}));
$$('input[name="publish"]').forEach(r=>r.addEventListener('change',()=>{$('#dateRow').style.display=r.value==='now'?'none':'grid'}));
const typeState={primary:'',secondary:[]};
$('#typeTrigger').addEventListener('click',()=>{const open=$('#typePanel').hidden;$('#typePanel').hidden=!open;$('#typeCascader').classList.toggle('open',open)});
$$('[data-primary]').forEach(btn=>btn.addEventListener('click',()=>{typeState.primary=btn.dataset.primary;$$('[data-primary]').forEach(x=>x.classList.toggle('selected',x===btn));const inside=typeState.primary==='inside';$('#outsideTypes').hidden=inside;['#ageRow','#radioRow'].forEach(id=>$(id).classList.toggle('is-hidden',inside));if(inside){typeState.secondary=[];$$('#outsideTypes input').forEach(x=>x.checked=false);$('#typeText').textContent='课内';$('#typePanel').hidden=true;$('#typeCascader').classList.remove('open')}else{updateTypeText()}}));
$$('#outsideTypes input').forEach(box=>box.addEventListener('change',()=>{typeState.secondary=$$('#outsideTypes input:checked').map(x=>x.value);updateTypeText()}));
function updateTypeText(){$('#typeText').textContent=typeState.primary==='outside'?(typeState.secondary.length?`课外 / ${typeState.secondary.join('、')}`:'课外 / 请选择'):'请选择类型'}
document.addEventListener('click',e=>{if(!$('#typeCascader').contains(e.target)){$('#typePanel').hidden=true;$('#typeCascader').classList.remove('open')}});
$$('[data-step]').forEach(btn=>btn.addEventListener('click',()=>{const input=btn.parentElement.querySelector('input');const next=Number(input.value||0)+Number(btn.dataset.step);input.value=Math.max(Number(input.min||0),Math.min(Number(input.max||Infinity),next))}));
$('#cover').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const url=URL.createObjectURL(file);$('#coverPreview').src=url;$('#coverPreview').hidden=false;$('#coverText').hidden=true;$('#largePreview').textContent='';$('#largePreview').style.backgroundImage=`url(${url})`});
$('#audioFile').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const player=$('#audioPreview');player.src=URL.createObjectURL(file);player.hidden=false;$('#audioText').hidden=true;player.onloadedmetadata=()=>{$('#duration').value=Math.round(player.duration||0)}});
form.addEventListener('submit',e=>{e.preventDefault();$$('.error').forEach(x=>x.classList.remove('error'));const missing=['cname','ename'].filter(id=>!$('#'+id).value.trim());if(missing.length){missing.forEach(id=>$('#'+id).classList.add('error'));show('请填写必填项',false);return}show('保存成功（原型演示）',true)});
form.addEventListener('reset',()=>setTimeout(()=>{$('#coverPreview').hidden=true;$('#coverText').hidden=false;$('#largePreview').style.backgroundImage='';$('#largePreview').textContent='353 × 353';$('#audioPreview').hidden=true;$('#audioText').hidden=false;$('#albumName').disabled=true;$('#dateRow').style.display='grid';typeState.primary='';typeState.secondary=[];$$('[data-primary]').forEach(x=>x.classList.remove('selected'));$$('#outsideTypes input').forEach(x=>x.checked=false);$('#outsideTypes').hidden=true;$('#typePanel').hidden=true;$('#typeCascader').classList.remove('open');$('#typeText').textContent='请选择类型';['#ageRow','#radioRow'].forEach(id=>$(id).classList.remove('is-hidden'));show('表单已重置',true)},0));
function show(text,ok){const t=$('#toast');t.textContent=text;t.style.color=ok?'#67c23a':'#f56c6c';t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
