const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const form=$('#fmForm'), initial=new FormData(form);
$('#collapse').addEventListener('click',()=>{$('#sidebar').classList.toggle('collapsed');document.querySelector('.page').classList.toggle('expanded')});
$$('input[name="album"]').forEach(r=>r.addEventListener('change',()=>{$('#albumName').disabled=r.value==='default'}));
$$('input[name="publish"]').forEach(r=>r.addEventListener('change',()=>{$('#dateRow').style.display=r.value==='now'?'none':'grid'}));
$('#typePrimary').addEventListener('change',e=>{const inside=e.target.value==='inside';const outside=e.target.value==='outside';$('#typeSecondary').hidden=!outside;if(!outside)resetOutsideTypes();$('#levelLegacy').hidden=inside;$('#levelCascade').hidden=!inside;if(inside){$('#levelPrimary').value='';$('#unitSelect').hidden=true;$('#lessonSelect').hidden=true}else{$('#levelLegacy').value='Level1'}['#ageRow','#radioRow'].forEach(id=>$(id).classList.toggle('is-hidden',inside))});
$('#outsideTrigger').addEventListener('click',()=>{const open=$('#outsideOptions').hidden;$('#outsideOptions').hidden=!open;$('#typeSecondary').classList.toggle('open',open)});
$$('#outsideOptions input').forEach(box=>box.addEventListener('change',()=>{const selected=$$('#outsideOptions input:checked').map(x=>x.value);$('#outsideText').textContent=selected.length?selected.join('、'):'请选择课外类型'}));
function resetOutsideTypes(){$$('#outsideOptions input').forEach(x=>x.checked=false);$('#outsideText').textContent='请选择课外类型';$('#outsideOptions').hidden=true;$('#typeSecondary').classList.remove('open')}
document.addEventListener('click',e=>{if(!$('#typeSecondary').contains(e.target)){$('#outsideOptions').hidden=true;$('#typeSecondary').classList.remove('open')}});
const fillOptions=(select,count,prefix)=>{select.innerHTML=`<option value="" selected disabled>请选择${prefix}</option>`;for(let i=1;i<=count;i++)select.add(new Option(`${prefix}${i}`,`${prefix}${i}`))};
$('#levelPrimary').addEventListener('change',e=>{const unitCount=e.target.value==='L1'?18:15;fillOptions($('#unitSelect'),unitCount,'Unit');$('#unitSelect').hidden=false;$('#lessonSelect').hidden=true;$('#lessonSelect').innerHTML='<option value="" selected disabled>请选择Lesson</option>'});
$('#unitSelect').addEventListener('change',()=>{const lessonCount=$('#levelPrimary').value==='L1'?8:10;fillOptions($('#lessonSelect'),lessonCount,'Lesson');$('#lessonSelect').hidden=false});
$$('[data-step]').forEach(btn=>btn.addEventListener('click',()=>{const input=btn.parentElement.querySelector('input');const next=Number(input.value||0)+Number(btn.dataset.step);input.value=Math.max(Number(input.min||0),Math.min(Number(input.max||Infinity),next))}));
$('#cover').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const url=URL.createObjectURL(file);$('#coverPreview').src=url;$('#coverPreview').hidden=false;$('#coverText').hidden=true;$('#largePreview').textContent='';$('#largePreview').style.backgroundImage=`url(${url})`});
$('#audioFile').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const player=$('#audioPreview');player.src=URL.createObjectURL(file);player.hidden=false;$('#audioText').hidden=true;player.onloadedmetadata=()=>{$('#duration').value=Math.round(player.duration||0)}});
form.addEventListener('submit',e=>{e.preventDefault();$$('.error').forEach(x=>x.classList.remove('error'));const missing=['cname','ename'].filter(id=>!$('#'+id).value.trim());if(missing.length){missing.forEach(id=>$('#'+id).classList.add('error'));show('请填写必填项',false);return}show('保存成功（原型演示）',true)});
form.addEventListener('reset',()=>setTimeout(()=>{$('#coverPreview').hidden=true;$('#coverText').hidden=false;$('#largePreview').style.backgroundImage='';$('#largePreview').textContent='353 × 353';$('#audioPreview').hidden=true;$('#audioText').hidden=false;$('#albumName').disabled=true;$('#dateRow').style.display='grid';$('#typePrimary').value='';resetOutsideTypes();$('#typeSecondary').hidden=true;$('#levelLegacy').hidden=false;$('#levelLegacy').value='Level1';$('#levelCascade').hidden=true;$('#levelPrimary').value='';$('#unitSelect').innerHTML='<option value="" selected disabled>请选择Unit</option>';$('#lessonSelect').innerHTML='<option value="" selected disabled>请选择Lesson</option>';$('#unitSelect').hidden=true;$('#lessonSelect').hidden=true;['#ageRow','#radioRow'].forEach(id=>$(id).classList.remove('is-hidden'));show('表单已重置',true)},0));
function show(text,ok){const t=$('#toast');t.textContent=text;t.style.color=ok?'#67c23a':'#f56c6c';t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
const requestedType=new URLSearchParams(location.search).get('type');
if(requestedType==='inside'||requestedType==='outside'){$('#typePrimary').value=requestedType;$('#typePrimary').dispatchEvent(new Event('change'));$('#formTitle').textContent=requestedType==='inside'?'新增课内FM音频':'新增课外FM音频'}
